{% set version = "0.4.0" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://github.com/benfred/py-spy/archive/v{{ version }}.tar.gz
  sha256: 13a5c4b949947425670eedac05b6dd27edbc736b75f1587899efca1a7ef79ac3

build:
  number: 0
  # Builds on Linux need a newer glibc: https://github.com/conda-forge/conda-forge.github.io/issues/900
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - libunwind  # [linux]
  run:
    - libunwind  # [linux]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
