{% set name = "py-spy" %}
{% set pypi_name = "py_spy" %}
{% set version = "0.4.1" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e53aa53daa2e47c2eef97dd2455b47bb3a7e7f962796a86cc3e7dbde8e6f4db4

build:
  number: 0
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - libunwind  # [linux]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - benfred
    - xhochy
