{% set name = "py-spy" %}
{% set pypi_name = "py_spy" %}
{% set version = "0.4.0" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 806602ce7972782cc9c1e383f339bfc27bfb822d42485e6a3e0530ae5040e1f0

build:
  number: 1
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - libunwind  # [linux]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - benfred
    - xhochy
